;; -*- mode: elisp-byte-code-mode; lexical-binding: t -*-

(package "eds"
         "0.1"
         "My small library of util code for emacs")

(website-url "https://github.com/eamonnsullivan/emacs.d")
(keywords "emacs" "config" "personal")

(files "lisp/eds-blog.el"
       "lisp/eds-email.el"
       "lisp/eds-org.el"
       "lisp/eds-utils.el")

(source "gnu")
(source "melpa")

(development
 (depends-on "undercover")
 (depends-on "buttercup"))
