;; -*- mode: eask; lexical-binding: t -*-

(package "init"
         "1.0.0"
         "Initialization code for emacs")

(website-url "https://github.com/eamonnsullivan/emacs.d")
(keywords "emacs" "config" "personal")

(package-file "init.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(development
  (depends-on "ert-runner")
  (depends-on "buttercup")
  (depends-on "el-mock"))
